[package]
name = "raybow-2"
version = "0.1.0"
edition = "2021"


[dependencies]
# Logging and debugging
log = "0.4.0"
env_logger = "0.10.0"

# Parsing cmd arguments
argh = "0.1.12"

# Randomness
rand = "0.8.5"
rand_xoshiro = "0.6.0"

# Math
glam = "0.27.0"